#!/usr/bin/env bash
# This script provides information about the school file
if [ -e "$file" ]; then
  echo "File '$file' exists."
  
  if [ -f "$file" ]; then
    echo "'$file' is a regular file."
  elif [ -d "$file" ]; then
    echo "'$file' is a directory."
  fi
  
  if [ -r "$file" ]; then
    echo "'$file' is readable."
  else
    echo "'$file' is not readable."
  fi
  
  if [ -w "$file" ]; then
    echo "'$file' is writable."
  else
    echo "'$file' is not writable."
  fi
  
  if [ -s "$file" ]; then
    echo "'$file' is not empty."
  else
    echo "'$file' is empty."
  fi

else
  echo "File '$file' does not exist."
fi
